Use GitHub/GitLab API to get a repo readme
charmbracelet/glow pull request #160
Opened 2020-10-03 23:29 UTC by cristiand391

2020-10-27 14:48 UTC, muesli commented
Thanks for your PR, @cristiand391! I'll try this out and review it asap!

2021-02-13 10:53 UTC, YerinAlexey requested changes

2021-02-13 10:53 UTC, YerinAlexey commented on gitlab.go
> +	apiRepoURL := fmt.Sprintf("https://gitlab.com/api/v4/projects/%s%s%s", user, "%2F", repo)
To be safe, this should probably be escaped.

Ref: [`url.PathEscape`](https://godocs.io/net/url#PathEscape)

```suggestion
	apiRepoURL := fmt.Sprintf("https://gitlab.com/api/v4/projects/%s", url.PathEscape(user + "/" + repo))
```

2021-02-13 10:53 UTC, YerinAlexey commented on gitlab.go
> +	if err := json.Unmarshal([]byte(string(content)), &repoInfo); err != nil {
This is useless conversion as `ioutil.ReadAll` already returns `[]byte`.

Ref: [`ioutil.ReadAll`](https://godocs.io/io/ioutil#ReadAll)

```suggestion
	if err := json.Unmarshal(content, &repoInfo); err != nil {
```

2021-02-13 10:53 UTC, YerinAlexey commented on utils.go
> +	pathSplit := strings.Split(u.Path, "/")
I think it is better to use [`path.Split`](https://godocs.io/path#Split) here as it will work on non-Unix systems as well.

2021-03-02 14:33 UTC, closed without merging